stages:
  prepare:
    cmd: python src/prepare.py dataset/data.xml
    deps:
    - src/prepare.py
    - dataset/data.xml
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - src/featurization.py
    - data/prepared
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features
  train:
    cmd: python src/train.py dataset/features model.pkl
    deps:
    - src/train.py
    - dataset/features
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
